### ISSUE TITLE
P0011: Looser restrictions on share rules

### ISSUE THREAD

**Issue by chuigda** [Pr47/doc47#13]
### Abstract
According to mind experments and previous discussions, we concluded that our restrictions on mutable shares is too strong, making it hard to write useful programs utilizing mutable shares. This proposal proposes a new restriction rule for mutable shares.

------

### Existing problems and workarounds
See #12 for more detail.

------

### This proposal's method

Replace the previous “orphan mutable-share rule” with the following rules:
- Prohibit Rust FFI functions from returning mutable reference (or make these functions unsafe)
- If a Rust FFI function accepts one &mut T and at least one &T, that function is unsafe.
- If a Rust FFI function accpets more than one &mut T, that function is unsafe.
- Returning mutably shared object to Rust is prohibited.

This will make many implementations easier.

------

### Unresolved problems
We've not proved the soundness of the rules above. What's more, this may be difficult for T10 to implement.

------

### See also
#12

**Comment by SchrodingerZhu** [comment]
@ICEYSELF 
[SUSPEND] Deeper Design Issue Spotted.

**Comment by SchrodingerZhu** [comment]
@ICEYSELF 
How do @lhmouse's asteria handle similar issues?

**Comment by chuigda** [comment]
According to our discussion, this proposal is totally useless against our design issue. DR0010 will be promoted to L3.

**Comment by CousinZe** [comment]
> How do lhmouse's asteria handle similar issues?

There is no "soundness" in C++ since the C++ language itself is unsafe.

**Comment by FrankHB** [comment]
> > How do lhmouse's asteria handle similar issues?
> 
> There is no "soundness" in C++ since the C++ language itself is unsafe.

Nope. Soundness is a property that a deduction system can guarantee all sentances it proves are correct as per the allowed semantic interpretations. There is no rules *inside* the system to govern which interpretations are intended. It is [up to](https://blog.ambrosebs.com/2018/04/09/unsoundness-reply.html) the meta system which defines the criteria.

In C++, the canonical one is the informative but normative specificaiton. It is clear that the language must not rule out undefined behaviors in the requirements of conformance, so "safety" is literally a non-goal. (This is also true for any languages with `unsafe`.) Instead, allowing unsafety of memory and any other stuff is a feature by design. The whole set of rules cannot be unsound it this sense.

*C++'s type system* is unsound to reason about whether a program is memory-safe/thread-safe/..., though. However, the precise statements like this are practically useless because: (1) you can always add arbitrary (additional) "safety" properties cannot handled by the type system; (2) safety guarantees can be implement without aids from the type system in the language, though the difficulties vary. (For a specific example, languages without the proper tail call guarantee are not safe up to the unbounded amount of nested tail calls, as the total space consumption of the activation records created in the active calls is not provable to be O(1).)
